# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

# Assignment 1: DataFrame Creation and Indexing

###1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

**importing pandas**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
np.random.seed(42)
data1 = np.random.randint(1, 100, size=(6, 4))
df1 = pd.DataFrame(data1, columns=['Col1', 'Col2', 'Col3', 'Col4'])
df1 = df1.set_index('Col1')
display(df1)

      Col2  Col3  Col4
Col1
52      93    15    72
61      21    83    87
75      75    88    24
3       22    53     2
88      30    38     2
64      60    21    33

###2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [ ]:
# 2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.
np.random.seed(42)
data2 = np.random.randint(1, 100, size=(3, 3))
df2 = pd.DataFrame(data2, columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])
element = df2.loc['Y', 'B']
display(df2)
print(f"Element at row 'Y' and column 'B': {element}")

    A   B   C
X  52  93  15
Y  72  61  21
Z  83  87  75

Element at row 'Y' and column 'B': 61

# Assignment 2: DataFrame Operations

### Task 1: Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [ ]:
np.random.seed(42)
df_ops1 = pd.DataFrame(np.random.randint(1, 50, size=(5, 3)), columns=['A', 'B', 'C'])
df_ops1['A_times_B'] = df_ops1['A'] * df_ops1['B']
display(df_ops1)

    A   B   C  A_times_B
0  39  29  15       1131
1  43   8  21        344
2  39  19  23        741
3  11  11  24        121
4  36  40  24       1440

### Task 2: Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [ ]:
np.random.seed(42)
df_ops2 = pd.DataFrame(np.random.randint(1, 50, size=(4, 3)), columns=['Col1', 'Col2', 'Col3'])
print("Original DataFrame:")
display(df_ops2)
print("\nRow-wise sum:")
print(df_ops2.sum(axis=1))
print("\nColumn-wise sum:")
print(df_ops2.sum(axis=0))

Original DataFrame:

   Col1  Col2  Col3
0    39    29    15
1    43     8    21
2    39    19    23
3    11    11    24

Row-wise sum:
0    83
1    72
2    81
3    46
dtype: int64

Column-wise sum:
Col1    132
Col2     67
Col3     83
dtype: int64

# Assignment 3: Data Cleaning

### Task 1: Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [ ]:
np.random.seed(42)
df_clean1 = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C']).astype(float)
df_clean1.iloc[1, 0] = np.nan
df_clean1.iloc[3, 2] = np.nan
print("DataFrame with NaNs:")
display(df_clean1)
print("\nDataFrame filled with Column Mean:")
df_clean1_filled = df_clean1.fillna(df_clean1.mean())
display(df_clean1_filled)

DataFrame with NaNs:

      A     B     C
0  52.0  93.0  15.0
1   NaN  61.0  21.0
2  83.0  87.0  75.0
3  75.0  88.0   NaN
4   3.0  22.0  53.0

DataFrame filled with Column Mean:

       A     B     C
0  52.00  93.0  15.0
1  53.25  61.0  21.0
2  83.00  87.0  75.0
3  75.00  88.0  41.0
4   3.00  22.0  53.0

### Task 2: Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [ ]:
np.random.seed(42)
df_clean2 = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)), columns=['A', 'B', 'C', 'D']).astype(float)
df_clean2.iloc[2, 1] = np.nan
df_clean2.iloc[4, 3] = np.nan
print("DataFrame with NaNs:")
display(df_clean2)
print("\nDataFrame after dropping rows with NaNs:")
df_clean2_dropped = df_clean2.dropna()
display(df_clean2_dropped)

DataFrame with NaNs:

      A     B     C     D
0  52.0  93.0  15.0  72.0
1  61.0  21.0  83.0  87.0
2  75.0   NaN  88.0  24.0
3   3.0  22.0  53.0   2.0
4  88.0  30.0  38.0   NaN
5  64.0  60.0  21.0  33.0

DataFrame after dropping rows with NaNs:

      A     B     C     D
0  52.0  93.0  15.0  72.0
1  61.0  21.0  83.0  87.0
3   3.0  22.0  53.0   2.0
5  64.0  60.0  21.0  33.0

# Assignment 4: Data Aggregation

### Task 1: Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [ ]:
np.random.seed(42)
categories = np.random.choice(['A', 'B', 'C'], size=10)
values = np.random.randint(10, 100, size=10)
df_agg1 = pd.DataFrame({'Category': categories, 'Value': values})
print("Original DataFrame:")
display(df_agg1)
print("\nAggregated Sum and Mean:")
grouped1 = df_agg1.groupby('Category')['Value'].agg(['sum', 'mean'])
display(grouped1)

Original DataFrame:

  Category  Value
0        C     84
1        A     84
2        C     97
3        C     33
4        A     12
5        A     31
6        C     62
7        B     11
8        C     97
9        C     39

Aggregated Sum and Mean:

          sum       mean
Category
A         127  42.333333
B          11  11.000000
C         412  68.666667

### Task 2: Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [ ]:
np.random.seed(42)
products = [f'Prod_{i}' for i in range(1, 9)]
categories = np.random.choice(['Electronics', 'Clothing', 'Home'], size=8)
sales = np.random.randint(100, 1000, size=8)
df_agg2 = pd.DataFrame({'Product': products, 'Category': categories, 'Sales': sales})
print("Original DataFrame:")
display(df_agg2)
print("\nTotal Sales per Category:")
total_sales = df_agg2.groupby('Category')['Sales'].sum().reset_index()
display(total_sales)

Original DataFrame:

  Product     Category  Sales
0  Prod_1         Home    566
1  Prod_2  Electronics    314
2  Prod_3         Home    430
3  Prod_4         Home    558
4  Prod_5  Electronics    187
5  Prod_6  Electronics    472
6  Prod_7         Home    199
7  Prod_8     Clothing    971

Total Sales per Category:

      Category  Sales
0     Clothing    971
1  Electronics    973
2         Home   1753

# Assignment 5: Merging DataFrames

### Task 1: Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [ ]:
df_left = pd.DataFrame({'Emp_ID': [101, 102, 103, 104], 'Name': ['Alice', 'Bob', 'Charlie', 'David']})
df_right = pd.DataFrame({'Emp_ID': [102, 103, 104, 105], 'Department': ['HR', 'IT', 'Finance', 'Marketing']})
print("Left DataFrame:")
display(df_left)
print("\nRight DataFrame:")
display(df_right)
print("\nMerged DataFrame (Inner Join):")
df_merged = pd.merge(df_left, df_right, on='Emp_ID')
display(df_merged)

Left DataFrame:

   Emp_ID     Name
0     101    Alice
1     102      Bob
2     103  Charlie
3     104    David

Right DataFrame:

   Emp_ID Department
0     102         HR
1     103         IT
2     104    Finance
3     105  Marketing

Merged DataFrame (Inner Join):

   Emp_ID     Name Department
0     102      Bob         HR
1     103  Charlie         IT
2     104    David    Finance

### Task 2: Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [ ]:
df_c1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df_c2 = pd.DataFrame({'C': [5, 6], 'D': [7, 8]})
print("DataFrame 1:")
display(df_c1)
print("\nDataFrame 2:")
display(df_c2)
print("\nConcatenation along Rows (axis=0):")
display(pd.concat([df_c1, df_c2], axis=0, sort=False))
print("\nConcatenation along Columns (axis=1):")
display(pd.concat([df_c1, df_c2], axis=1))

DataFrame 1:

   A  B
0  1  3
1  2  4

DataFrame 2:

   C  D
0  5  7
1  6  8

Concatenation along Rows (axis=0):

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

Concatenation along Columns (axis=1):

   A  B  C  D
0  1  3  5  7
1  2  4  6  8

# Assignment 6: Time Series Analysis

### Task 1: Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [ ]:
np.random.seed(42)
dates_daily = pd.date_range(start='2023-01-01', end='2023-06-30', freq='D')
df_ts1 = pd.DataFrame(np.random.randint(10, 100, size=len(dates_daily)), index=dates_daily, columns=['Value'])
print("First 5 rows of daily data:")
display(df_ts1.head())
print("\nMonthly Mean Resampled:")
df_monthly = df_ts1.resample('M').mean()
display(df_monthly)

First 5 rows of daily data:

            Value
2023-01-01     61
2023-01-02     24
2023-01-03     81
2023-01-04     70
2023-01-05     30

Monthly Mean Resampled:

/tmp/ipykernel_4930/1647116268.py:7: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_monthly = df_ts1.resample('M').mean()

                Value
2023-01-31  58.161290
2023-02-28  55.071429
2023-03-31  57.612903
2023-04-30  52.100000
2023-05-31  52.129032
2023-06-30  54.400000

### Task 2: Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [ ]:
np.random.seed(42)
dates_2021 = pd.date_range(start='2021-01-01', end='2021-12-31', freq='D')
df_ts2 = pd.DataFrame(np.random.randint(10, 100, size=len(dates_2021)), index=dates_2021, columns=['Value'])
df_ts2['7D_Rolling_Mean'] = df_ts2['Value'].rolling(window=7).mean()
print("Showing head of the rolling calculations (first 10 days):")
display(df_ts2.head(10))

Showing head of the rolling calculations (first 10 days):

            Value  7D_Rolling_Mean
2021-01-01     61              NaN
2021-01-02     24              NaN
2021-01-03     81              NaN
2021-01-04     70              NaN
2021-01-05     30              NaN
2021-01-06     92              NaN
2021-01-07     96        64.857143
2021-01-08     84        68.142857
2021-01-09     84        76.714286
2021-01-10     97        79.000000

# Assignment 7: MultiIndex DataFrame

### Task 1: Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [ ]:
arrays = [
    ['Group1', 'Group1', 'Group2', 'Group2'],
    ['SubA', 'SubB', 'SubA', 'SubB']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Main', 'Sub'))
df_mi1 = pd.DataFrame({'Value': [10, 20, 30, 40]}, index=index)
print("MultiIndex DataFrame:")
display(df_mi1)
print("\nIndexing 'Group1':")
display(df_mi1.loc['Group1'])
print("\nSlicing 'Group1' to 'Group2' for SubA:")
display(df_mi1.xs('SubA', level='Sub'))

MultiIndex DataFrame:

             Value
Main   Sub
Group1 SubA     10
       SubB     20
Group2 SubA     30
       SubB     40

Indexing 'Group1':

      Value
Sub
SubA     10
SubB     20

Slicing 'Group1' to 'Group2' for SubA:

        Value
Main
Group1     10
Group2     30

### Task 2: Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [ ]:
np.random.seed(42)
categories = ['Furniture', 'Furniture', 'Office Supplies', 'Office Supplies']
subcategories = ['Chairs', 'Tables', 'Paper', 'Pens']
mi = pd.MultiIndex.from_arrays([categories, subcategories], names=['Category', 'SubCategory'])
df_mi2 = pd.DataFrame({'Sales': np.random.randint(50, 500, size=4)}, index=mi)
print("MultiIndex Sales DataFrame:")
display(df_mi2)
print("\nSum of values aggregated by Category:")
display(df_mi2.groupby(level='Category').sum())

MultiIndex Sales DataFrame:

                             Sales
Category        SubCategory
Furniture       Chairs         152
                Tables         485
Office Supplies Paper          398
                Pens           320

Sum of values aggregated by Category:

                 Sales
Category
Furniture          637
Office Supplies    718

# Assignment 8: Pivot Tables

### Task 1: Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [ ]:
data_pivot1 = {
    'Date': ['2023-10-01', '2023-10-01', '2023-10-02', '2023-10-02', '2023-10-01'],
    'Category': ['A', 'B', 'A', 'B', 'A'],
    'Value': [10, 20, 30, 40, 15]
}
df_p1 = pd.DataFrame(data_pivot1)
print("Original DataFrame:")
display(df_p1)
pivot_table1 = df_p1.pivot_table(values='Value', index='Date', columns='Category', aggfunc='sum')
print("\nPivot Table (Sum of Value):")
display(pivot_table1)

Original DataFrame:

         Date Category  Value
0  2023-10-01        A     10
1  2023-10-01        B     20
2  2023-10-02        A     30
3  2023-10-02        B     40
4  2023-10-01        A     15

Pivot Table (Sum of Value):

Category     A   B
Date
2023-10-01  25  20
2023-10-02  30  40

### Task 2: Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [ ]:
data_pivot2 = {
    'Year': [2021, 2021, 2021, 2022, 2022, 2022],
    'Quarter': ['Q1', 'Q2', 'Q1', 'Q1', 'Q2', 'Q2'],
    'Revenue': [100, 150, 120, 200, 250, 270]
}
df_p2 = pd.DataFrame(data_pivot2)
print("Original DataFrame:")
display(df_p2)
pivot_table2 = df_p2.pivot_table(values='Revenue', index='Year', columns='Quarter', aggfunc='mean')
print("\nPivot Table (Mean Revenue):")
display(pivot_table2)

Original DataFrame:

   Year Quarter  Revenue
0  2021      Q1      100
1  2021      Q2      150
2  2021      Q1      120
3  2022      Q1      200
4  2022      Q2      250
5  2022      Q2      270

Pivot Table (Mean Revenue):

Quarter     Q1     Q2
Year
2021     110.0  150.0
2022     200.0  260.0

# Assignment 9: Applying Functions

### Task 1: Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [ ]:
np.random.seed(42)
df_apply1 = pd.DataFrame(np.random.randint(1, 20, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
display(df_apply1)
print("\nDataFrame with values doubled:")
double_func = lambda x: x * 2
display(df_apply1.apply(double_func))

Original DataFrame:

    A   B   C
0   7  15  11
1   8   7  19
2  11  11   4
3   8   3   2
4  12   6   2

DataFrame with values doubled:

    A   B   C
0  14  30  22
1  16  14  38
2  22  22   8
3  16   6   4
4  24  12   4

### Task 2: Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [ ]:
np.random.seed(42)
df_apply2 = pd.DataFrame(np.random.randint(1, 20, size=(6, 3)), columns=['X', 'Y', 'Z'])
df_apply2['Row_Sum'] = df_apply2.apply(lambda row: row['X'] + row['Y'] + row['Z'], axis=1)
print("DataFrame with row-wise sum column:")
display(df_apply2)

DataFrame with row-wise sum column:

    X   Y   Z  Row_Sum
0   7  15  11       33
1   8   7  19       34
2  11  11   4       26
3   8   3   2       13
4  12   6   2       20
5   1  12  12       25

# Assignment 10: Working with Text Data

### Task 1: Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [ ]:
text_series1 = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Original Series:")
print(text_series1)
print("\nUppercase Series:")
print(text_series1.str.upper())

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: object

Uppercase Series:
0         APPLE
1        BANANA
2        CHERRY
3          DATE
4    ELDERBERRY
dtype: object

### Task 2: Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [ ]:
text_series2 = pd.Series(['elephant', 'giraffe', 'hippopotamus', 'jaguar', 'kangaroo'])
print("Original Series:")
print(text_series2)
print("\nFirst three characters:")
print(text_series2.str[:3])

Original Series:
0        elephant
1         giraffe
2    hippopotamus
3          jaguar
4        kangaroo
dtype: object

First three characters:
0    ele
1    gir
2    hip
3    jag
4    kan
dtype: object